# --- BUILD STAGE ---
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy project file & restore
COPY *.csproj ./
RUN dotnet restore

# Copy source & publish
COPY . ./
RUN dotnet publish -c Release -o out

# --- RUNTIME STAGE ---
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copy build output
COPY --from=build /app/out ./

# Tạo thư mục chứa video upload
RUN mkdir -p /app/Video

# Cấu hình cổng
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# Chạy app
ENTRYPOINT ["dotnet", "StreamVideo.dll"]
