version: '3.9'

services:
  streamvideo:
    build:
      context: .
      dockerfile: dockerfile.yml
    ports:
      - "5036:8080"
    volumes:
      - ./Video:/app/Video  # Đồng bộ thư mục video host <-> container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
